// SpaceInvaders.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include "pch.h"
#include <iostream>
#include "GameEngine.h"
#include "GSSpaceInvaders.h"

using namespace std;

//A showcase spaceInvaders Game state
GSSpaceInvaders space = GSSpaceInvaders();
//A showcase dodgeball game state.
GameStateJump jump = GameStateJump();

//A simple function which makes Space Invaders the active Game State and then runs it.
void spaceInvaders();
//A simple function which makes Dodgeball the active Game State and then runs it.
void dodgeball();

int main()
{
	spaceInvaders(); //Space invaders is just what we are demonstrating now.
	//dodgeball(); Makes showing dodgeball easier so just uncomment this.

	return 0;
}

//Creates and starts space invaders.
void spaceInvaders() {
	cout << "Space Invaders. \n";
	game::state = &space;
	game::gameLoop();
	cout << "End Space Invaders. \n";
}

//Creates and starts dodgeball.
void dodgeball() {
	cout << "Dodgeball. \n";
	game::state = &jump;
	game::gameLoop();
	cout << "End Dodgeball. \n";
}

//Auto generated by visual studio.
// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
